name: basic-server
base: core22
version: '0.1'
summary: Simple server that greets clients
description: |
  basic-server is a simple server that listens on its configured port, sends
  "Hello, world!", and disconnects from the client.

grade: stable
confinement: strict

apps:
  daemon:
    command: usr/bin/server.sh
    daemon: simple
    install-mode: enable
    plugs:
      - network-bind

parts:
  src:
    plugin: dump
    source: ./src
    organize:
      server.sh: usr/bin/server.sh

  ncat:
    plugin: nil
    stage-packages:
      - ncat
    stage:
      - -usr/share
      - -usr/lib/${CRAFT_ARCH_TRIPLET}/liblua5.3-c++*
